export const colorClasses = [
    "bg-indigo-600",
    "bg-purple-600",
    "bg-pink-600",
    "bg-rose-600",
    "bg-red-600",
    "bg-orange-600",
    "bg-amber-600",
    "bg-green-600",
    "bg-emerald-600",
    "bg-teal-600",
    "bg-cyan-600",
    "bg-blue-600",
];

export const getRandomColor = () => {
    return colorClasses[Math.floor(Math.random() * colorClasses.length)];
};

//all course page categories JSON list.
export const allCategories = [
    "Programming",
    "Computer Science",
    "Web Development",
    "Database",
    "Cybersecurity",
    "AI & Machine Learning",
    "Mobile Development",
    "Cloud Computing",
    "Networking",
    "DevOps",
    "Data Science",
    "Game Development",
    "Blockchain",
    "Design",
    "Software Engineering",
    "Computer Vision",
    "IoT",
    "Graphics",
    "System Architecture",
    "Big Data",
    "Robotics",
    "Quantum Computing",
    "Backend Development",
    "AR/VR"
];

//tags filter data for all courses page
export const allTags = [
    "Python",
    "Programming",
    "Beginner",
    "Algorithms",
    "Data Structures",
    "Problem Solving",
    "React",
    "JavaScript",
    "Frontend",
    "SQL",
    "Database",
    "Data Management",
    "Security",
    "Cybersecurity",
    "Network Protection",
    "Machine Learning",
    "TensorFlow",
    "AI",
    "Flutter",
    "Mobile",
    "Cross-platform",
    "AWS",
    "Cloud",
    "Infrastructure",
    "Networking",
    "Protocols",
    "DevOps",
    "CI/CD",
    "Automation",
    "Data Science",
    "Analytics",
    "Unity",
    "Game Development",
    "C#",
    "Operating Systems",
    "System Programming",
    "Computer Science",
    "Blockchain",
    "Cryptocurrency",
    "Smart Contracts",
    "UX Design",
    "User Interface",
    "Design Thinking",
    "AI Ethics",
    "Technology Ethics",
    "Philosophy",
    "Testing",
    "QA",
    "Software Engineering",
    "Image Processing",
    "Computer Vision",
    "OpenCV",
    "IoT",
    "Arduino",
    "Sensors",
    "3D Graphics",
    "Modeling",
    "Animation",
    "NLP",
    "Deep Learning",
    "Text Processing",
    "Distributed Systems",
    "Microservices",
    "Scalability",
    "Big Data",
    "Hadoop",
    "Compilers",
    "Programming Languages",
    "Theory",
    "Robotics",
    "Control Systems",
    "Quantum Computing",
    "Quantum Algorithms",
    "Physics",
    "API",
    "REST",
    "GraphQL",
    "Augmented Reality",
    "ARKit",
    "Architecture",
    "Design Patterns",
    "Ethical Hacking",
    "Penetration Testing",
    "Intermediate",
    "Advanced",
    "English"
];


export const pricingPlans = [
    {
        name: "FREE",
        price: "$0",
        period: "/month",
        users: "2 user",
        features: [
            { text: "Learning Scope", available: true },
            { text: "Team collaboration", available: false },
            { text: "Export HTML code", available: false },
            { text: "Upload Your Logo", available: true },
        ],
        buttonColor: "bg-purple-600",
    },
    {
        name: "BASIC",
        price: "$29",
        period: "/month",
        users: "5 user",
        features: [
            { text: "Learning Scope", available: true },
            { text: "Team collaboration", available: true },
            { text: "Export HTML code", available: false },
            { text: "Upload Your Logo", available: true },
        ],
        buttonColor: "bg-pink-500",
    },
    {
        name: "PRO",
        price: "$59",
        period: "/month",
        users: "2 user",
        features: [
            { text: "Learning Scope", available: true },
            { text: "Team collaboration", available: true },
            { text: "Export HTML code", available: true },
            { text: "Upload Your Logo", available: true },
        ],
        buttonColor: "bg-purple-600",
    },
];